ESPSerialHandler:
  port: "/dev/ttyUSB0"
  baudrate: 115200
  pubSocket: "/tmp/pub_esp_serial_handler.socket"
  subSocket: "10.227.159.191"
  subPort: 5000
  verbose: false

PICOSerialHandler:
  port: "/dev/ttyACM0"
  baudrate: 115200
  socketPath: "/tmp/pico_serial_handler.socket"
  verbose: false