global:
  modules_path: "modules"

ESPSerialHandler:
  enbled: true
  args:
    -p: "/dev/ttyUSB0"                  #serial port
    -b: 115200                          #baudrate
    --pub-socket: "/tmp/pub_esp_serial_handler.socket" #zmq publish socket path
    --sub-socket: "/tmp/sub_esp_serial_handler.socket"      #zmq subscribe to socket path (either IPC path or IP for TCP or UDP)
    #--sub-socket: "10.227.144.223"      #zmq subscribe to socket path (either IPC path or IP for TCP or UDP)
    #--sub-port: 5000                    #zmq subscribe to port (if path is tcp or udp)
  flags:
    verbose: true

PICOSerialHandler:
  enabled: true
  args:
    -p: "/dev/ttyACM0"                    #serial port
    -b: 115200                            #baudrate
    -s: "/tmp/pico_serial_handler.socket" #zmq socket path
  flags:
    verbose: false